//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Reworked Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ReworkedControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ReworkedControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Reworked Controls"",
    ""maps"": [
        {
            ""name"": ""Normal"",
            ""id"": ""2c093099-ca1e-4a05-b2db-30b3c47440e4"",
            ""actions"": [
                {
                    ""name"": ""TouchPress"",
                    ""type"": ""Button"",
                    ""id"": ""3118323f-c3cd-42db-a967-907accf18e3d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TouchPosition"",
                    ""type"": ""Value"",
                    ""id"": ""1080ca67-bb0b-4eae-88fb-bd727c0da678"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TouchDoubleTap"",
                    ""type"": ""Button"",
                    ""id"": ""d01bf5c6-8bfe-45d1-a115-2b397e5396ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TouchSlowTap"",
                    ""type"": ""Button"",
                    ""id"": ""7119c147-4ab6-4f38-affe-916de1762096"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""SlowTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Touch"",
                    ""type"": ""Value"",
                    ""id"": ""3b8c6f27-5468-4946-bd83-36ff75abd8aa"",
                    ""expectedControlType"": ""Touch"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dd9493aa-06ff-4b6f-8d6e-765607b7cb8c"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55087318-6d19-4d86-817c-c903d2692162"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""14dfe59d-f46a-4352-a20f-c722352cc120"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a8d198c-7a6a-43f0-963e-e4edb1419ef6"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3e8dfb9a-ebf2-41ed-82a6-d6a01a8c12f2"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchDoubleTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c2a11ed-025e-4b8f-a9c9-b5590615cdb8"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchDoubleTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d681571-2ffc-454a-9edc-6a1082244c90"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchSlowTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50ef2a7c-b67a-4356-9975-cbf207d175f1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchSlowTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e3f9bfb-6baa-495b-b1ac-379597befe7f"",
                    ""path"": ""<Touchscreen>/primaryTouch"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Normal
        m_Normal = asset.FindActionMap("Normal", throwIfNotFound: true);
        m_Normal_TouchPress = m_Normal.FindAction("TouchPress", throwIfNotFound: true);
        m_Normal_TouchPosition = m_Normal.FindAction("TouchPosition", throwIfNotFound: true);
        m_Normal_TouchDoubleTap = m_Normal.FindAction("TouchDoubleTap", throwIfNotFound: true);
        m_Normal_TouchSlowTap = m_Normal.FindAction("TouchSlowTap", throwIfNotFound: true);
        m_Normal_Touch = m_Normal.FindAction("Touch", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Normal
    private readonly InputActionMap m_Normal;
    private INormalActions m_NormalActionsCallbackInterface;
    private readonly InputAction m_Normal_TouchPress;
    private readonly InputAction m_Normal_TouchPosition;
    private readonly InputAction m_Normal_TouchDoubleTap;
    private readonly InputAction m_Normal_TouchSlowTap;
    private readonly InputAction m_Normal_Touch;
    public struct NormalActions
    {
        private @ReworkedControls m_Wrapper;
        public NormalActions(@ReworkedControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @TouchPress => m_Wrapper.m_Normal_TouchPress;
        public InputAction @TouchPosition => m_Wrapper.m_Normal_TouchPosition;
        public InputAction @TouchDoubleTap => m_Wrapper.m_Normal_TouchDoubleTap;
        public InputAction @TouchSlowTap => m_Wrapper.m_Normal_TouchSlowTap;
        public InputAction @Touch => m_Wrapper.m_Normal_Touch;
        public InputActionMap Get() { return m_Wrapper.m_Normal; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(NormalActions set) { return set.Get(); }
        public void SetCallbacks(INormalActions instance)
        {
            if (m_Wrapper.m_NormalActionsCallbackInterface != null)
            {
                @TouchPress.started -= m_Wrapper.m_NormalActionsCallbackInterface.OnTouchPress;
                @TouchPress.performed -= m_Wrapper.m_NormalActionsCallbackInterface.OnTouchPress;
                @TouchPress.canceled -= m_Wrapper.m_NormalActionsCallbackInterface.OnTouchPress;
                @TouchPosition.started -= m_Wrapper.m_NormalActionsCallbackInterface.OnTouchPosition;
                @TouchPosition.performed -= m_Wrapper.m_NormalActionsCallbackInterface.OnTouchPosition;
                @TouchPosition.canceled -= m_Wrapper.m_NormalActionsCallbackInterface.OnTouchPosition;
                @TouchDoubleTap.started -= m_Wrapper.m_NormalActionsCallbackInterface.OnTouchDoubleTap;
                @TouchDoubleTap.performed -= m_Wrapper.m_NormalActionsCallbackInterface.OnTouchDoubleTap;
                @TouchDoubleTap.canceled -= m_Wrapper.m_NormalActionsCallbackInterface.OnTouchDoubleTap;
                @TouchSlowTap.started -= m_Wrapper.m_NormalActionsCallbackInterface.OnTouchSlowTap;
                @TouchSlowTap.performed -= m_Wrapper.m_NormalActionsCallbackInterface.OnTouchSlowTap;
                @TouchSlowTap.canceled -= m_Wrapper.m_NormalActionsCallbackInterface.OnTouchSlowTap;
                @Touch.started -= m_Wrapper.m_NormalActionsCallbackInterface.OnTouch;
                @Touch.performed -= m_Wrapper.m_NormalActionsCallbackInterface.OnTouch;
                @Touch.canceled -= m_Wrapper.m_NormalActionsCallbackInterface.OnTouch;
            }
            m_Wrapper.m_NormalActionsCallbackInterface = instance;
            if (instance != null)
            {
                @TouchPress.started += instance.OnTouchPress;
                @TouchPress.performed += instance.OnTouchPress;
                @TouchPress.canceled += instance.OnTouchPress;
                @TouchPosition.started += instance.OnTouchPosition;
                @TouchPosition.performed += instance.OnTouchPosition;
                @TouchPosition.canceled += instance.OnTouchPosition;
                @TouchDoubleTap.started += instance.OnTouchDoubleTap;
                @TouchDoubleTap.performed += instance.OnTouchDoubleTap;
                @TouchDoubleTap.canceled += instance.OnTouchDoubleTap;
                @TouchSlowTap.started += instance.OnTouchSlowTap;
                @TouchSlowTap.performed += instance.OnTouchSlowTap;
                @TouchSlowTap.canceled += instance.OnTouchSlowTap;
                @Touch.started += instance.OnTouch;
                @Touch.performed += instance.OnTouch;
                @Touch.canceled += instance.OnTouch;
            }
        }
    }
    public NormalActions @Normal => new NormalActions(this);
    public interface INormalActions
    {
        void OnTouchPress(InputAction.CallbackContext context);
        void OnTouchPosition(InputAction.CallbackContext context);
        void OnTouchDoubleTap(InputAction.CallbackContext context);
        void OnTouchSlowTap(InputAction.CallbackContext context);
        void OnTouch(InputAction.CallbackContext context);
    }
}
